# Generated by Django 4.1.1 on 2022-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersmodel_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='user_age',
            field=models.IntegerField(default=True),
        ),
    ]
