# Generated by Django 4.1.2 on 2022-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersmodel_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='user_phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='전화번호'),
        ),
    ]
