# Generated by Django 4.1.2 on 2022-11-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usersmodel_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='user_name',
            field=models.CharField(max_length=16, unique=True, verbose_name='유저 이름'),
        ),
    ]
